[package]
name = "mcx-hal"
version = "0.0.1"
edition = "2021"
authors = ["Logiase Song <logiase.songs@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
paste = "1.0.14"
embedded-hal = "1"

# pacs
mcxn947-pac = { version = "*", optional = true }

[dev-dependencies]
panic-halt = "0.2.0"

[features]
n947 = ["dep:mcxn947-pac"]
n947rt = ["n947", "mcxn947-pac/rt"]
