use crate::pac::*;
use crate::syscon::periph_en_define;

periph_en_define! {
    (periph: inputmux::INPUTMUX0, 0,  0, hRST: true, hCC: true, hACC: true)
    (periph: i3c::I3C0,           0,  1, hRST: true, hCC: true, hACC: true)
    (periph: ctimer::CTIMER0,     0,  2, hRST: true, hCC: true, hACC: true)
    (periph: ctimer::CTIMER1,     0,  3, hRST: true, hCC: true, hACC: true)
    (periph: ctimer::CTIMER2,     0,  4, hRST: true, hCC: true, hACC: true)
    (periph: freqme::FREQME0,     0,  5, hRST: true, hCC: true, hACC: true)
    (periph: utick::UTICK0,       0,  6, hRST: true, hCC: true, hACC: true)
    (periph: dma::DMA0,           0,  8, hRST: true, hCC: true, hACC: true)
    (periph: aoi::AOI0,           0,  9, hRST: true, hCC: true, hACC: true)
    (periph: crc::CRC0,           0, 10, hRST: true, hCC: true, hACC: true)
    (periph: eim::EIM0,           0, 11, hRST: true, hCC: true, hACC: true)
    (periph: erm::ERM0,           0, 12, hRST: true, hCC: true, hACC: true)
    (periph: lpi2c::LPI2C0,       0, 16, hRST: true, hCC: true, hACC: true)
    (periph: lpspi::LPSPI0,       0, 17, hRST: true, hCC: true, hACC: true)
    (periph: lpspi::LPSPI1,       0, 18, hRST: true, hCC: true, hACC: true)
    (periph: lpuart::LPUART0,     0, 19, hRST: true, hCC: true, hACC: true)
    (periph: lpuart::LPUART1,     0, 20, hRST: true, hCC: true, hACC: true)
    (periph: lpuart::LPUART2,     0, 21, hRST: true, hCC: true, hACC: true)
    (periph: usb::USB0,           0, 22, hRST: true, hCC: true, hACC: true)
    (periph: eqdc::QDC0,          0, 23, hRST: true, hCC: true, hACC: true)
    (periph: pwm::FLEXPWM0,       0, 24, hRST: true, hCC: true, hACC: true)
    (periph: ostimer::OSTIMER0,   0, 25, hRST: true, hCC: true, hACC: true)
    (periph: adc::ADC0,           0, 26, hRST: true, hCC: true, hACC: true)
    (periph: lpcmp::CMP0,         0, 27,             hCC: true, hACC: true)
    (periph: lpcmp::CMP1,         0, 28, hRST: true, hCC: true, hACC: true)
    (periph: port::PORT0,         0, 29, hRST: true, hCC: true, hACC: true)
    (periph: port::PORT1,         0, 30, hRST: true, hCC: true, hACC: true)
    (periph: port::PORT2,         0, 31, hRST: true, hCC: true, hACC: true)

    (periph: port::PORT3,         1,  0, hRST: true, hCC: true, hACC: true)
    (virt: RAMA,                  1,  4,             hCC: true, hACC: true)
    (periph: gpio::GPIO0,         1,  5, hRST: true, hCC: true, hACC: true)
    (periph: gpio::GPIO1,         1,  6, hRST: true, hCC: true, hACC: true)
    (periph: gpio::GPIO2,         1,  7, hRST: true, hCC: true, hACC: true)
    (periph: gpio::GPIO3,         1,  8, hRST: true, hCC: true, hACC: true)
    (virt: ROMCP,                 1,  9,             hCC: true, hACC: true)
}
