use super::{mrcc_periph_en_define, PeripheralACC, PeripheralCC, PeripheralMRCC, PeripheralRST};
use crate::pac::*;

mrcc_periph_en_define! {
    (periph: inputmux::INPUTMUX0, 0,  0, hRST: true, hCC: true, hACC: true)
    (periph: i3c::I3C0,           0,  1, hRST: true, hCC: true, hACC: true)
    (periph: ctimer::CTIMER0,     0,  2, hRST: true, hCC: true, hACC: true)
    (periph: ctimer::CTIMER1,     0,  3, hRST: true, hCC: true, hACC: true)
    (periph: ctimer::CTIMER2,     0,  4, hRST: true, hCC: true, hACC: true)
    (periph: ctimer::CTIMER3,     0,  5, hRST: true, hCC: true, hACC: true)
    (periph: ctimer::CTIMER4,     0,  6, hRST: true, hCC: true, hACC: true)
    (periph: freqme::FREQME0,     0,  7, hRST: true, hCC: true, hACC: true)
    (periph: utick::UTICK0,       0,  8, hRST: true, hCC: true, hACC: true)
    (periph: dma::DMA0,           0, 10, hRST: true, hCC: true, hACC: true)
    (periph: aoi::AOI0,           0, 11, hRST: true, hCC: true, hACC: true)
    (periph: crc::CRC0,           0, 12, hRST: true, hCC: true, hACC: true)
    (periph: eim::EIM0,           0, 13, hRST: true, hCC: true, hACC: true)
    (periph: erm::ERM0,           0, 14, hRST: true, hCC: true, hACC: true)
    (periph: aoi::AOI1,           0, 16, hRST: true, hCC: true)
    (periph: flexio::FLEXIO0,     0, 17, hRST: true, hCC: true)
    (periph: lpi2c::LPI2C0,       0, 18, hRST: true, hCC: true, hACC: true)
    (periph: lpi2c::LPI2C1,       0, 19, hRST: true, hCC: true, hACC: true)
    (periph: lpspi::LPSPI0,       0, 20, hRST: true, hCC: true, hACC: true)
    (periph: lpspi::LPSPI1,       0, 21, hRST: true, hCC: true, hACC: true)
    (periph: lpuart::LPUART0,     0, 22, hRST: true, hCC: true, hACC: true)
    (periph: lpuart::LPUART1,     0, 23, hRST: true, hCC: true, hACC: true)
    (periph: lpuart::LPUART2,     0, 24, hRST: true, hCC: true, hACC: true)
    (periph: lpuart::LPUART3,     0, 25, hRST: true, hCC: true, hACC: true)
    (periph: lpuart::LPUART4,     0, 26, hRST: true, hCC: true, hACC: true)
    (periph: usb::USB0,           0, 27, hRST: true, hCC: true, hACC: true)
    (periph: eqdc::QDC0,          0, 28, hRST: true, hCC: true, hACC: true)
    (periph: eqdc::QDC1,          0, 29, hRST: true, hCC: true, hACC: true)
    (periph: pwm::FLEXPWM0,       0, 30, hRST: true, hCC: true, hACC: true)
    (periph: pwm::FLEXPWM1,       0, 31, hRST: true, hCC: true, hACC: true)

    (periph: ostimer::OSTIMER0,   1,  0, hRST: true, hCC: true, hACC: true)
    (periph: adc::ADC0,           1,  1, hRST: true, hCC: true, hACC: true)
    (periph: adc::ADC1,           1,  2, hRST: true, hCC: true, hACC: true)
    (periph: lpcmp::CMP0,         1,  3,             hCC: true, hACC: true)
    (periph: lpcmp::CMP1,         1,  4, hRST: true, hCC: true, hACC: true)
    (periph: lpdac::DAC0,         1,  5, hRST: true, hCC: true, hACC: true)
    (periph: opamp::OPAMP0,       1,  6, hRST: true, hCC: true, hACC: true)
    (periph: port::PORT0,         1,  7, hRST: true, hCC: true, hACC: true)
    (periph: port::PORT1,         1,  8, hRST: true, hCC: true, hACC: true)
    (periph: port::PORT2,         1,  9, hRST: true, hCC: true, hACC: true)
    (periph: port::PORT3,         1, 10, hRST: true, hCC: true, hACC: true)
    (periph: port::PORT4,         1, 11, hRST: true, hCC: true, hACC: true)
    (periph: can::CAN0,           1, 12, hRST: true, hCC: true, hACC: true)
    (periph: lpi2c::LPI2C2,       1, 13, hRST: true, hCC: true, hACC: true)
    (periph: lpi2c::LPI2C3,       1, 14, hRST: true, hCC: true, hACC: true)
    (virt: RAMA,                  1, 18,             hCC: true, hACC: true)
    (virt: RAMB,                  1, 18,             hCC: true, hACC: true)
    (periph: gpio::GPIO0,         1, 20, hRST: true, hCC: true, hACC: true)
    (periph: gpio::GPIO1,         1, 21, hRST: true, hCC: true, hACC: true)
    (periph: gpio::GPIO2,         1, 22, hRST: true, hCC: true, hACC: true)
    (periph: gpio::GPIO3,         1, 23, hRST: true, hCC: true, hACC: true)
    (periph: gpio::GPIO4,         1, 24, hRST: true, hCC: true, hACC: true)
    (virt: ROMC,                  1, 25,             hCC: true, hACC: true)
}
